// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="convert_10to8,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7k325t-ffg900-2,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=4.332875,HLS_SYN_LAT=34,HLS_SYN_TPT=1,HLS_SYN_MEM=2,HLS_SYN_DSP=56,HLS_SYN_FF=7376,HLS_SYN_LUT=6792,HLS_VERSION=2019_1}" *)

module convert_10to8 (
        ap_clk,
        ap_rst,
        i_data_y_V,
        i_data_cb_V,
        i_data_cr_V,
        o_data_r_V,
        o_data_g_V,
        o_data_b_V
);


input   ap_clk;
input   ap_rst;
input  [9:0] i_data_y_V;
input  [9:0] i_data_cb_V;
input  [9:0] i_data_cr_V;
output  [7:0] o_data_r_V;
output  [7:0] o_data_g_V;
output  [7:0] o_data_b_V;

reg   [9:0] i_data_y_V_read_reg_1209;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_state23_pp0_stage0_iter22;
wire    ap_block_state24_pp0_stage0_iter23;
wire    ap_block_state25_pp0_stage0_iter24;
wire    ap_block_state26_pp0_stage0_iter25;
wire    ap_block_state27_pp0_stage0_iter26;
wire    ap_block_state28_pp0_stage0_iter27;
wire    ap_block_state29_pp0_stage0_iter28;
wire    ap_block_state30_pp0_stage0_iter29;
wire    ap_block_state31_pp0_stage0_iter30;
wire    ap_block_state32_pp0_stage0_iter31;
wire    ap_block_state33_pp0_stage0_iter32;
wire    ap_block_state34_pp0_stage0_iter33;
wire    ap_block_state35_pp0_stage0_iter34;
wire    ap_block_pp0_stage0_11001;
reg   [9:0] i_data_y_V_read_reg_1209_pp0_iter1_reg;
reg   [9:0] i_data_y_V_read_reg_1209_pp0_iter2_reg;
reg   [9:0] i_data_y_V_read_reg_1209_pp0_iter3_reg;
reg   [9:0] i_data_y_V_read_reg_1209_pp0_iter4_reg;
reg   [9:0] i_data_y_V_read_reg_1209_pp0_iter5_reg;
reg   [9:0] i_data_y_V_read_reg_1209_pp0_iter6_reg;
wire   [63:0] grp_fu_177_p1;
reg   [63:0] tmp_reg_1224;
reg   [63:0] tmp_reg_1224_pp0_iter6_reg;
reg   [63:0] tmp_reg_1224_pp0_iter7_reg;
reg   [63:0] tmp_reg_1224_pp0_iter8_reg;
reg   [63:0] tmp_reg_1224_pp0_iter9_reg;
reg   [63:0] tmp_reg_1224_pp0_iter10_reg;
reg   [63:0] tmp_reg_1224_pp0_iter11_reg;
reg   [63:0] tmp_reg_1224_pp0_iter12_reg;
reg   [63:0] tmp_reg_1224_pp0_iter13_reg;
wire   [63:0] grp_fu_180_p1;
reg   [63:0] tmp_3_reg_1230;
wire   [10:0] y_V_fu_211_p2;
reg   [10:0] y_V_reg_1236;
wire   [63:0] grp_fu_157_p2;
reg   [63:0] i_op_assign_reg_1246;
wire   [63:0] grp_fu_183_p1;
reg   [63:0] tmp_1_reg_1251;
wire   [63:0] grp_fu_162_p2;
reg   [63:0] i_op_assign_1_reg_1258;
wire   [63:0] grp_fu_167_p2;
reg   [63:0] i_op_assign_2_reg_1263;
wire   [63:0] grp_fu_141_p2;
reg   [63:0] val_assign_reg_1268;
wire   [63:0] grp_fu_145_p2;
reg   [63:0] tmp_4_reg_1273;
wire   [63:0] grp_fu_172_p2;
reg   [63:0] tmp_5_reg_1278;
wire   [63:0] grp_fu_149_p2;
reg   [63:0] val_assign_2_reg_1283;
wire   [63:0] reg_V_fu_221_p1;
reg   [63:0] reg_V_reg_1288;
reg   [63:0] reg_V_reg_1288_pp0_iter23_reg;
reg   [0:0] p_Result_5_reg_1294;
reg   [0:0] p_Result_5_reg_1294_pp0_iter23_reg;
reg   [0:0] p_Result_5_reg_1294_pp0_iter24_reg;
wire   [11:0] trunc_ln331_fu_250_p1;
reg   [11:0] trunc_ln331_reg_1299;
reg   [11:0] trunc_ln331_reg_1299_pp0_iter23_reg;
wire   [0:0] icmp_ln326_fu_254_p2;
reg   [0:0] icmp_ln326_reg_1305;
reg   [0:0] icmp_ln326_reg_1305_pp0_iter23_reg;
wire  signed [11:0] sh_amt_fu_260_p2;
reg  signed [11:0] sh_amt_reg_1312;
wire   [0:0] icmp_ln330_fu_266_p2;
reg   [0:0] icmp_ln330_reg_1320;
reg   [0:0] icmp_ln330_reg_1320_pp0_iter23_reg;
wire   [63:0] reg_V_2_fu_272_p1;
reg   [63:0] reg_V_2_reg_1326;
reg   [63:0] reg_V_2_reg_1326_pp0_iter23_reg;
reg   [0:0] p_Result_7_reg_1332;
reg   [0:0] p_Result_7_reg_1332_pp0_iter23_reg;
reg   [0:0] p_Result_7_reg_1332_pp0_iter24_reg;
wire   [11:0] trunc_ln331_2_fu_301_p1;
reg   [11:0] trunc_ln331_2_reg_1337;
reg   [11:0] trunc_ln331_2_reg_1337_pp0_iter23_reg;
wire   [0:0] icmp_ln326_2_fu_305_p2;
reg   [0:0] icmp_ln326_2_reg_1343;
reg   [0:0] icmp_ln326_2_reg_1343_pp0_iter23_reg;
wire  signed [11:0] sh_amt_4_fu_311_p2;
reg  signed [11:0] sh_amt_4_reg_1350;
wire   [0:0] icmp_ln330_2_fu_317_p2;
reg   [0:0] icmp_ln330_2_reg_1358;
reg   [0:0] icmp_ln330_2_reg_1358_pp0_iter23_reg;
wire   [0:0] icmp_ln333_fu_342_p2;
reg   [0:0] icmp_ln333_reg_1364;
wire  signed [11:0] sh_amt_1_fu_347_p2;
reg  signed [11:0] sh_amt_1_reg_1369;
wire   [0:0] and_ln332_fu_382_p2;
reg   [0:0] and_ln332_reg_1374;
wire   [11:0] select_ln333_fu_394_p3;
reg   [11:0] select_ln333_reg_1379;
wire   [0:0] and_ln343_fu_414_p2;
reg   [0:0] and_ln343_reg_1384;
wire   [0:0] icmp_ln333_2_fu_439_p2;
reg   [0:0] icmp_ln333_2_reg_1389;
wire  signed [11:0] sh_amt_5_fu_444_p2;
reg  signed [11:0] sh_amt_5_reg_1394;
wire   [0:0] and_ln332_2_fu_479_p2;
reg   [0:0] and_ln332_2_reg_1399;
wire   [11:0] select_ln333_4_fu_491_p3;
reg   [11:0] select_ln333_4_reg_1404;
wire   [0:0] and_ln343_2_fu_511_p2;
reg   [0:0] and_ln343_2_reg_1409;
wire   [11:0] select_ln330_fu_585_p3;
reg   [11:0] select_ln330_reg_1414;
wire   [11:0] select_ln330_2_fu_660_p3;
reg   [11:0] select_ln330_2_reg_1420;
reg   [0:0] tmp_20_reg_1426;
reg   [7:0] trunc_ln1371_1_reg_1431;
reg   [7:0] trunc_ln1371_2_reg_1436;
reg   [0:0] tmp_22_reg_1441;
reg   [7:0] trunc_ln1371_7_reg_1446;
reg   [7:0] trunc_ln1371_8_reg_1451;
wire   [7:0] select_ln1371_fu_862_p3;
reg   [7:0] select_ln1371_reg_1456;
reg   [7:0] select_ln1371_reg_1456_pp0_iter27_reg;
reg   [7:0] select_ln1371_reg_1456_pp0_iter28_reg;
reg   [7:0] select_ln1371_reg_1456_pp0_iter29_reg;
reg   [7:0] select_ln1371_reg_1456_pp0_iter30_reg;
reg   [7:0] select_ln1371_reg_1456_pp0_iter31_reg;
reg   [7:0] select_ln1371_reg_1456_pp0_iter32_reg;
reg   [7:0] select_ln1371_reg_1456_pp0_iter33_reg;
wire   [7:0] select_ln1371_2_fu_873_p3;
reg   [7:0] select_ln1371_2_reg_1461;
reg   [7:0] select_ln1371_2_reg_1461_pp0_iter27_reg;
reg   [7:0] select_ln1371_2_reg_1461_pp0_iter28_reg;
reg   [7:0] select_ln1371_2_reg_1461_pp0_iter29_reg;
reg   [7:0] select_ln1371_2_reg_1461_pp0_iter30_reg;
reg   [7:0] select_ln1371_2_reg_1461_pp0_iter31_reg;
reg   [7:0] select_ln1371_2_reg_1461_pp0_iter32_reg;
reg   [7:0] select_ln1371_2_reg_1461_pp0_iter33_reg;
wire   [63:0] grp_fu_153_p2;
reg   [63:0] val_assign_1_reg_1466;
wire   [63:0] reg_V_1_fu_879_p1;
reg   [63:0] reg_V_1_reg_1471;
reg   [63:0] reg_V_1_reg_1471_pp0_iter31_reg;
reg   [0:0] p_Result_6_reg_1477;
reg   [0:0] p_Result_6_reg_1477_pp0_iter31_reg;
reg   [0:0] p_Result_6_reg_1477_pp0_iter32_reg;
wire   [11:0] trunc_ln331_1_fu_908_p1;
reg   [11:0] trunc_ln331_1_reg_1482;
reg   [11:0] trunc_ln331_1_reg_1482_pp0_iter31_reg;
wire   [0:0] icmp_ln326_1_fu_912_p2;
reg   [0:0] icmp_ln326_1_reg_1488;
reg   [0:0] icmp_ln326_1_reg_1488_pp0_iter31_reg;
wire  signed [11:0] sh_amt_2_fu_918_p2;
reg  signed [11:0] sh_amt_2_reg_1495;
wire   [0:0] icmp_ln330_1_fu_924_p2;
reg   [0:0] icmp_ln330_1_reg_1503;
reg   [0:0] icmp_ln330_1_reg_1503_pp0_iter31_reg;
wire   [0:0] icmp_ln333_1_fu_949_p2;
reg   [0:0] icmp_ln333_1_reg_1509;
wire  signed [11:0] sh_amt_3_fu_954_p2;
reg  signed [11:0] sh_amt_3_reg_1514;
wire   [0:0] and_ln332_1_fu_989_p2;
reg   [0:0] and_ln332_1_reg_1519;
wire   [11:0] select_ln333_2_fu_1001_p3;
reg   [11:0] select_ln333_2_reg_1524;
wire   [0:0] and_ln343_1_fu_1021_p2;
reg   [0:0] and_ln343_1_reg_1529;
wire   [11:0] select_ln330_1_fu_1095_p3;
reg   [11:0] select_ln330_1_reg_1534;
reg   [0:0] tmp_21_reg_1540;
reg   [7:0] trunc_ln1371_4_reg_1545;
reg   [7:0] trunc_ln1371_5_reg_1550;
wire    ap_block_pp0_stage0_01001;
wire    ap_block_pp0_stage0;
wire  signed [31:0] grp_fu_177_p0;
wire  signed [31:0] grp_fu_180_p0;
wire  signed [31:0] grp_fu_183_p0;
wire   [9:0] cr_V_fu_192_p2;
wire   [9:0] cb_V_fu_186_p2;
wire   [10:0] zext_ln68_fu_208_p1;
wire   [10:0] p_Result_s_fu_236_p4;
wire   [62:0] trunc_ln310_fu_224_p1;
wire   [11:0] exp_V_fu_246_p1;
wire   [10:0] p_Result_8_fu_287_p4;
wire   [62:0] trunc_ln310_2_fu_275_p1;
wire   [11:0] exp_V_2_fu_297_p1;
wire   [51:0] trunc_ln318_fu_323_p1;
wire  signed [31:0] sext_ln329_fu_334_p1;
wire   [52:0] tmp_2_fu_326_p3;
wire   [52:0] zext_ln334_fu_358_p1;
wire   [52:0] lshr_ln334_fu_362_p2;
wire   [0:0] or_ln330_fu_372_p2;
wire   [0:0] icmp_ln332_fu_337_p2;
wire   [0:0] xor_ln330_fu_376_p2;
wire   [0:0] and_ln333_fu_388_p2;
wire   [11:0] trunc_ln334_fu_368_p1;
wire   [0:0] or_ln332_fu_402_p2;
wire   [0:0] icmp_ln343_fu_352_p2;
wire   [0:0] xor_ln332_fu_408_p2;
wire   [51:0] trunc_ln318_2_fu_420_p1;
wire  signed [31:0] sext_ln329_2_fu_431_p1;
wire   [52:0] tmp_7_fu_423_p3;
wire   [52:0] zext_ln334_2_fu_455_p1;
wire   [52:0] lshr_ln334_2_fu_459_p2;
wire   [0:0] or_ln330_2_fu_469_p2;
wire   [0:0] icmp_ln332_2_fu_434_p2;
wire   [0:0] xor_ln330_2_fu_473_p2;
wire   [0:0] and_ln333_4_fu_485_p2;
wire   [11:0] trunc_ln334_2_fu_465_p1;
wire   [0:0] or_ln332_2_fu_499_p2;
wire   [0:0] icmp_ln343_2_fu_449_p2;
wire   [0:0] xor_ln332_2_fu_505_p2;
wire   [0:0] tmp_9_fu_520_p3;
wire  signed [31:0] sext_ln342_fu_517_p1;
wire   [11:0] sext_ln342cast_fu_535_p1;
wire   [11:0] shl_ln345_fu_539_p2;
wire   [11:0] select_ln343_fu_544_p3;
wire   [0:0] xor_ln333_fu_557_p2;
wire   [0:0] and_ln333_1_fu_562_p2;
wire   [11:0] select_ln336_fu_527_p3;
wire   [11:0] select_ln326_fu_550_p3;
wire   [0:0] xor_ln326_fu_575_p2;
wire   [0:0] and_ln330_fu_580_p2;
wire   [11:0] select_ln333_1_fu_567_p3;
wire   [0:0] tmp_13_fu_595_p3;
wire  signed [31:0] sext_ln342_2_fu_592_p1;
wire   [11:0] sext_ln342_2cast_fu_610_p1;
wire   [11:0] shl_ln345_2_fu_614_p2;
wire   [11:0] select_ln343_2_fu_619_p3;
wire   [0:0] xor_ln333_2_fu_632_p2;
wire   [0:0] and_ln333_5_fu_637_p2;
wire   [11:0] select_ln336_2_fu_602_p3;
wire   [11:0] select_ln326_2_fu_625_p3;
wire   [0:0] xor_ln326_2_fu_650_p2;
wire   [0:0] and_ln330_2_fu_655_p2;
wire   [11:0] select_ln333_5_fu_642_p3;
wire   [11:0] sub_ln461_fu_667_p2;
wire   [11:0] sub_ln461_2_fu_678_p2;
wire   [11:0] r_V_fu_672_p3;
wire   [1:0] tmp_15_fu_697_p4;
wire   [0:0] tmp_14_fu_689_p3;
wire   [0:0] icmp_ln895_fu_707_p2;
wire   [0:0] or_ln887_fu_725_p2;
wire   [10:0] select_ln887_fu_717_p3;
wire   [10:0] empty_fu_713_p1;
wire   [11:0] b_V_fu_683_p3;
wire   [1:0] tmp_19_fu_747_p4;
wire   [0:0] tmp_18_fu_739_p3;
wire   [0:0] icmp_ln895_2_fu_757_p2;
wire   [0:0] or_ln887_2_fu_775_p2;
wire   [10:0] select_ln887_4_fu_767_p3;
wire   [10:0] empty_9_fu_763_p1;
wire   [10:0] select_ln887_1_fu_731_p3;
wire   [10:0] sub_ln1371_fu_797_p2;
wire   [10:0] select_ln887_5_fu_781_p3;
wire   [10:0] sub_ln1371_4_fu_831_p2;
wire   [7:0] sub_ln1371_1_fu_857_p2;
wire   [7:0] sub_ln1371_5_fu_868_p2;
wire   [10:0] p_Result_4_fu_894_p4;
wire   [62:0] trunc_ln310_1_fu_882_p1;
wire   [11:0] exp_V_1_fu_904_p1;
wire   [51:0] trunc_ln318_1_fu_930_p1;
wire  signed [31:0] sext_ln329_1_fu_941_p1;
wire   [52:0] tmp_6_fu_933_p3;
wire   [52:0] zext_ln334_1_fu_965_p1;
wire   [52:0] lshr_ln334_1_fu_969_p2;
wire   [0:0] or_ln330_1_fu_979_p2;
wire   [0:0] icmp_ln332_1_fu_944_p2;
wire   [0:0] xor_ln330_1_fu_983_p2;
wire   [0:0] and_ln333_2_fu_995_p2;
wire   [11:0] trunc_ln334_1_fu_975_p1;
wire   [0:0] or_ln332_1_fu_1009_p2;
wire   [0:0] icmp_ln343_1_fu_959_p2;
wire   [0:0] xor_ln332_1_fu_1015_p2;
wire   [0:0] tmp_11_fu_1030_p3;
wire  signed [31:0] sext_ln342_1_fu_1027_p1;
wire   [11:0] sext_ln342_1cast_fu_1045_p1;
wire   [11:0] shl_ln345_1_fu_1049_p2;
wire   [11:0] select_ln343_1_fu_1054_p3;
wire   [0:0] xor_ln333_1_fu_1067_p2;
wire   [0:0] and_ln333_3_fu_1072_p2;
wire   [11:0] select_ln336_1_fu_1037_p3;
wire   [11:0] select_ln326_1_fu_1060_p3;
wire   [0:0] xor_ln326_1_fu_1085_p2;
wire   [0:0] and_ln330_1_fu_1090_p2;
wire   [11:0] select_ln333_3_fu_1077_p3;
wire   [11:0] sub_ln461_1_fu_1102_p2;
wire   [11:0] g_V_fu_1107_p3;
wire   [1:0] tmp_17_fu_1121_p4;
wire   [0:0] tmp_16_fu_1113_p3;
wire   [0:0] icmp_ln895_1_fu_1131_p2;
wire   [0:0] or_ln887_1_fu_1149_p2;
wire   [10:0] select_ln887_2_fu_1141_p3;
wire   [10:0] empty_8_fu_1137_p1;
wire   [10:0] select_ln887_3_fu_1155_p3;
wire   [10:0] sub_ln1371_2_fu_1171_p2;
wire   [7:0] sub_ln1371_3_fu_1197_p2;

convert_10to8_dadbkb #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
convert_10to8_dadbkb_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_1_reg_1251),
    .din1(i_op_assign_reg_1246),
    .ce(1'b1),
    .dout(grp_fu_141_p2)
);

convert_10to8_dsucud #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
convert_10to8_dsucud_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_1_reg_1251),
    .din1(i_op_assign_1_reg_1258),
    .ce(1'b1),
    .dout(grp_fu_145_p2)
);

convert_10to8_dadbkb #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
convert_10to8_dadbkb_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_1_reg_1251),
    .din1(i_op_assign_2_reg_1263),
    .ce(1'b1),
    .dout(grp_fu_149_p2)
);

convert_10to8_dsucud #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
convert_10to8_dsucud_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_4_reg_1273),
    .din1(tmp_5_reg_1278),
    .ce(1'b1),
    .dout(grp_fu_153_p2)
);

convert_10to8_dmudEe #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
convert_10to8_dmudEe_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_reg_1224),
    .din1(64'd4608992865850220347),
    .ce(1'b1),
    .dout(grp_fu_157_p2)
);

convert_10to8_dmudEe #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
convert_10to8_dmudEe_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_3_reg_1230),
    .din1(64'd4599868573005167722),
    .ce(1'b1),
    .dout(grp_fu_162_p2)
);

convert_10to8_dmudEe #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
convert_10to8_dmudEe_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_3_reg_1230),
    .din1(64'd4610663701311974801),
    .ce(1'b1),
    .dout(grp_fu_167_p2)
);

convert_10to8_dmudEe #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
convert_10to8_dmudEe_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_reg_1224_pp0_iter13_reg),
    .din1(64'd4604606359813161484),
    .ce(1'b1),
    .dout(grp_fu_172_p2)
);

convert_10to8_siteOg #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
convert_10to8_siteOg_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_177_p0),
    .ce(1'b1),
    .dout(grp_fu_177_p1)
);

convert_10to8_siteOg #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
convert_10to8_siteOg_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_180_p0),
    .ce(1'b1),
    .dout(grp_fu_180_p1)
);

convert_10to8_siteOg #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
convert_10to8_siteOg_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_183_p0),
    .ce(1'b1),
    .dout(grp_fu_183_p1)
);

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln332_1_reg_1519 <= and_ln332_1_fu_989_p2;
        and_ln332_2_reg_1399 <= and_ln332_2_fu_479_p2;
        and_ln332_reg_1374 <= and_ln332_fu_382_p2;
        i_data_y_V_read_reg_1209 <= i_data_y_V;
        i_data_y_V_read_reg_1209_pp0_iter1_reg <= i_data_y_V_read_reg_1209;
        i_data_y_V_read_reg_1209_pp0_iter2_reg <= i_data_y_V_read_reg_1209_pp0_iter1_reg;
        i_data_y_V_read_reg_1209_pp0_iter3_reg <= i_data_y_V_read_reg_1209_pp0_iter2_reg;
        i_data_y_V_read_reg_1209_pp0_iter4_reg <= i_data_y_V_read_reg_1209_pp0_iter3_reg;
        i_data_y_V_read_reg_1209_pp0_iter5_reg <= i_data_y_V_read_reg_1209_pp0_iter4_reg;
        i_data_y_V_read_reg_1209_pp0_iter6_reg <= i_data_y_V_read_reg_1209_pp0_iter5_reg;
        i_op_assign_1_reg_1258 <= grp_fu_162_p2;
        i_op_assign_2_reg_1263 <= grp_fu_167_p2;
        i_op_assign_reg_1246 <= grp_fu_157_p2;
        icmp_ln326_1_reg_1488 <= icmp_ln326_1_fu_912_p2;
        icmp_ln326_1_reg_1488_pp0_iter31_reg <= icmp_ln326_1_reg_1488;
        icmp_ln326_2_reg_1343 <= icmp_ln326_2_fu_305_p2;
        icmp_ln326_2_reg_1343_pp0_iter23_reg <= icmp_ln326_2_reg_1343;
        icmp_ln326_reg_1305 <= icmp_ln326_fu_254_p2;
        icmp_ln326_reg_1305_pp0_iter23_reg <= icmp_ln326_reg_1305;
        icmp_ln330_1_reg_1503 <= icmp_ln330_1_fu_924_p2;
        icmp_ln330_1_reg_1503_pp0_iter31_reg <= icmp_ln330_1_reg_1503;
        icmp_ln330_2_reg_1358 <= icmp_ln330_2_fu_317_p2;
        icmp_ln330_2_reg_1358_pp0_iter23_reg <= icmp_ln330_2_reg_1358;
        icmp_ln330_reg_1320 <= icmp_ln330_fu_266_p2;
        icmp_ln330_reg_1320_pp0_iter23_reg <= icmp_ln330_reg_1320;
        icmp_ln333_1_reg_1509 <= icmp_ln333_1_fu_949_p2;
        icmp_ln333_2_reg_1389 <= icmp_ln333_2_fu_439_p2;
        icmp_ln333_reg_1364 <= icmp_ln333_fu_342_p2;
        p_Result_5_reg_1294 <= reg_V_fu_221_p1[32'd63];
        p_Result_5_reg_1294_pp0_iter23_reg <= p_Result_5_reg_1294;
        p_Result_5_reg_1294_pp0_iter24_reg <= p_Result_5_reg_1294_pp0_iter23_reg;
        p_Result_6_reg_1477 <= reg_V_1_fu_879_p1[32'd63];
        p_Result_6_reg_1477_pp0_iter31_reg <= p_Result_6_reg_1477;
        p_Result_6_reg_1477_pp0_iter32_reg <= p_Result_6_reg_1477_pp0_iter31_reg;
        p_Result_7_reg_1332 <= reg_V_2_fu_272_p1[32'd63];
        p_Result_7_reg_1332_pp0_iter23_reg <= p_Result_7_reg_1332;
        p_Result_7_reg_1332_pp0_iter24_reg <= p_Result_7_reg_1332_pp0_iter23_reg;
        reg_V_1_reg_1471 <= reg_V_1_fu_879_p1;
        reg_V_1_reg_1471_pp0_iter31_reg <= reg_V_1_reg_1471;
        reg_V_2_reg_1326 <= reg_V_2_fu_272_p1;
        reg_V_2_reg_1326_pp0_iter23_reg <= reg_V_2_reg_1326;
        reg_V_reg_1288 <= reg_V_fu_221_p1;
        reg_V_reg_1288_pp0_iter23_reg <= reg_V_reg_1288;
        select_ln1371_2_reg_1461 <= select_ln1371_2_fu_873_p3;
        select_ln1371_2_reg_1461_pp0_iter27_reg <= select_ln1371_2_reg_1461;
        select_ln1371_2_reg_1461_pp0_iter28_reg <= select_ln1371_2_reg_1461_pp0_iter27_reg;
        select_ln1371_2_reg_1461_pp0_iter29_reg <= select_ln1371_2_reg_1461_pp0_iter28_reg;
        select_ln1371_2_reg_1461_pp0_iter30_reg <= select_ln1371_2_reg_1461_pp0_iter29_reg;
        select_ln1371_2_reg_1461_pp0_iter31_reg <= select_ln1371_2_reg_1461_pp0_iter30_reg;
        select_ln1371_2_reg_1461_pp0_iter32_reg <= select_ln1371_2_reg_1461_pp0_iter31_reg;
        select_ln1371_2_reg_1461_pp0_iter33_reg <= select_ln1371_2_reg_1461_pp0_iter32_reg;
        select_ln1371_reg_1456 <= select_ln1371_fu_862_p3;
        select_ln1371_reg_1456_pp0_iter27_reg <= select_ln1371_reg_1456;
        select_ln1371_reg_1456_pp0_iter28_reg <= select_ln1371_reg_1456_pp0_iter27_reg;
        select_ln1371_reg_1456_pp0_iter29_reg <= select_ln1371_reg_1456_pp0_iter28_reg;
        select_ln1371_reg_1456_pp0_iter30_reg <= select_ln1371_reg_1456_pp0_iter29_reg;
        select_ln1371_reg_1456_pp0_iter31_reg <= select_ln1371_reg_1456_pp0_iter30_reg;
        select_ln1371_reg_1456_pp0_iter32_reg <= select_ln1371_reg_1456_pp0_iter31_reg;
        select_ln1371_reg_1456_pp0_iter33_reg <= select_ln1371_reg_1456_pp0_iter32_reg;
        select_ln330_1_reg_1534 <= select_ln330_1_fu_1095_p3;
        select_ln330_2_reg_1420 <= select_ln330_2_fu_660_p3;
        select_ln330_reg_1414 <= select_ln330_fu_585_p3;
        sh_amt_2_reg_1495 <= sh_amt_2_fu_918_p2;
        sh_amt_4_reg_1350 <= sh_amt_4_fu_311_p2;
        sh_amt_reg_1312 <= sh_amt_fu_260_p2;
        tmp_1_reg_1251 <= grp_fu_183_p1;
        tmp_20_reg_1426 <= select_ln887_1_fu_731_p3[32'd10];
        tmp_21_reg_1540 <= select_ln887_3_fu_1155_p3[32'd10];
        tmp_22_reg_1441 <= select_ln887_5_fu_781_p3[32'd10];
        tmp_3_reg_1230 <= grp_fu_180_p1;
        tmp_4_reg_1273 <= grp_fu_145_p2;
        tmp_5_reg_1278 <= grp_fu_172_p2;
        tmp_reg_1224 <= grp_fu_177_p1;
        tmp_reg_1224_pp0_iter10_reg <= tmp_reg_1224_pp0_iter9_reg;
        tmp_reg_1224_pp0_iter11_reg <= tmp_reg_1224_pp0_iter10_reg;
        tmp_reg_1224_pp0_iter12_reg <= tmp_reg_1224_pp0_iter11_reg;
        tmp_reg_1224_pp0_iter13_reg <= tmp_reg_1224_pp0_iter12_reg;
        tmp_reg_1224_pp0_iter6_reg <= tmp_reg_1224;
        tmp_reg_1224_pp0_iter7_reg <= tmp_reg_1224_pp0_iter6_reg;
        tmp_reg_1224_pp0_iter8_reg <= tmp_reg_1224_pp0_iter7_reg;
        tmp_reg_1224_pp0_iter9_reg <= tmp_reg_1224_pp0_iter8_reg;
        trunc_ln1371_1_reg_1431 <= {{sub_ln1371_fu_797_p2[9:2]}};
        trunc_ln1371_2_reg_1436 <= {{select_ln887_1_fu_731_p3[9:2]}};
        trunc_ln1371_4_reg_1545 <= {{sub_ln1371_2_fu_1171_p2[9:2]}};
        trunc_ln1371_5_reg_1550 <= {{select_ln887_3_fu_1155_p3[9:2]}};
        trunc_ln1371_7_reg_1446 <= {{sub_ln1371_4_fu_831_p2[9:2]}};
        trunc_ln1371_8_reg_1451 <= {{select_ln887_5_fu_781_p3[9:2]}};
        trunc_ln331_1_reg_1482 <= trunc_ln331_1_fu_908_p1;
        trunc_ln331_1_reg_1482_pp0_iter31_reg <= trunc_ln331_1_reg_1482;
        trunc_ln331_2_reg_1337 <= trunc_ln331_2_fu_301_p1;
        trunc_ln331_2_reg_1337_pp0_iter23_reg <= trunc_ln331_2_reg_1337;
        trunc_ln331_reg_1299 <= trunc_ln331_fu_250_p1;
        trunc_ln331_reg_1299_pp0_iter23_reg <= trunc_ln331_reg_1299;
        val_assign_1_reg_1466 <= grp_fu_153_p2;
        val_assign_2_reg_1283 <= grp_fu_149_p2;
        val_assign_reg_1268 <= grp_fu_141_p2;
        y_V_reg_1236 <= y_V_fu_211_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln326_1_reg_1488 == 1'd0))) begin
        and_ln343_1_reg_1529 <= and_ln343_1_fu_1021_p2;
        select_ln333_2_reg_1524 <= select_ln333_2_fu_1001_p3;
        sh_amt_3_reg_1514 <= sh_amt_3_fu_954_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln326_2_reg_1343 == 1'd0))) begin
        and_ln343_2_reg_1409 <= and_ln343_2_fu_511_p2;
        select_ln333_4_reg_1404 <= select_ln333_4_fu_491_p3;
        sh_amt_5_reg_1394 <= sh_amt_5_fu_444_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln326_reg_1305 == 1'd0))) begin
        and_ln343_reg_1384 <= and_ln343_fu_414_p2;
        select_ln333_reg_1379 <= select_ln333_fu_394_p3;
        sh_amt_1_reg_1369 <= sh_amt_1_fu_347_p2;
    end
end

assign and_ln330_1_fu_1090_p2 = (xor_ln326_1_fu_1085_p2 & icmp_ln330_1_reg_1503_pp0_iter31_reg);

assign and_ln330_2_fu_655_p2 = (xor_ln326_2_fu_650_p2 & icmp_ln330_2_reg_1358_pp0_iter23_reg);

assign and_ln330_fu_580_p2 = (xor_ln326_fu_575_p2 & icmp_ln330_reg_1320_pp0_iter23_reg);

assign and_ln332_1_fu_989_p2 = (xor_ln330_1_fu_983_p2 & icmp_ln332_1_fu_944_p2);

assign and_ln332_2_fu_479_p2 = (xor_ln330_2_fu_473_p2 & icmp_ln332_2_fu_434_p2);

assign and_ln332_fu_382_p2 = (xor_ln330_fu_376_p2 & icmp_ln332_fu_337_p2);

assign and_ln333_1_fu_562_p2 = (xor_ln333_fu_557_p2 & and_ln332_reg_1374);

assign and_ln333_2_fu_995_p2 = (icmp_ln333_1_fu_949_p2 & and_ln332_1_fu_989_p2);

assign and_ln333_3_fu_1072_p2 = (xor_ln333_1_fu_1067_p2 & and_ln332_1_reg_1519);

assign and_ln333_4_fu_485_p2 = (icmp_ln333_2_fu_439_p2 & and_ln332_2_fu_479_p2);

assign and_ln333_5_fu_637_p2 = (xor_ln333_2_fu_632_p2 & and_ln332_2_reg_1399);

assign and_ln333_fu_388_p2 = (icmp_ln333_fu_342_p2 & and_ln332_fu_382_p2);

assign and_ln343_1_fu_1021_p2 = (xor_ln332_1_fu_1015_p2 & icmp_ln343_1_fu_959_p2);

assign and_ln343_2_fu_511_p2 = (xor_ln332_2_fu_505_p2 & icmp_ln343_2_fu_449_p2);

assign and_ln343_fu_414_p2 = (xor_ln332_fu_408_p2 & icmp_ln343_fu_352_p2);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter28 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage0_iter29 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter30 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage0_iter31 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage0_iter32 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage0_iter33 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage0_iter34 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign b_V_fu_683_p3 = ((p_Result_7_reg_1332_pp0_iter24_reg[0:0] === 1'b1) ? sub_ln461_2_fu_678_p2 : select_ln330_2_reg_1420);

assign cb_V_fu_186_p2 = (i_data_cb_V ^ 10'd512);

assign cr_V_fu_192_p2 = (i_data_cr_V ^ 10'd512);

assign empty_8_fu_1137_p1 = g_V_fu_1107_p3[10:0];

assign empty_9_fu_763_p1 = b_V_fu_683_p3[10:0];

assign empty_fu_713_p1 = r_V_fu_672_p3[10:0];

assign exp_V_1_fu_904_p1 = p_Result_4_fu_894_p4;

assign exp_V_2_fu_297_p1 = p_Result_8_fu_287_p4;

assign exp_V_fu_246_p1 = p_Result_s_fu_236_p4;

assign g_V_fu_1107_p3 = ((p_Result_6_reg_1477_pp0_iter32_reg[0:0] === 1'b1) ? sub_ln461_1_fu_1102_p2 : select_ln330_1_reg_1534);

assign grp_fu_177_p0 = $signed(cr_V_fu_192_p2);

assign grp_fu_180_p0 = $signed(cb_V_fu_186_p2);

assign grp_fu_183_p0 = $signed(y_V_reg_1236);

assign icmp_ln326_1_fu_912_p2 = ((trunc_ln310_1_fu_882_p1 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln326_2_fu_305_p2 = ((trunc_ln310_2_fu_275_p1 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln326_fu_254_p2 = ((trunc_ln310_fu_224_p1 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln330_1_fu_924_p2 = ((p_Result_4_fu_894_p4 == 11'd1075) ? 1'b1 : 1'b0);

assign icmp_ln330_2_fu_317_p2 = ((p_Result_8_fu_287_p4 == 11'd1075) ? 1'b1 : 1'b0);

assign icmp_ln330_fu_266_p2 = ((p_Result_s_fu_236_p4 == 11'd1075) ? 1'b1 : 1'b0);

assign icmp_ln332_1_fu_944_p2 = (($signed(sh_amt_2_reg_1495) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln332_2_fu_434_p2 = (($signed(sh_amt_4_reg_1350) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln332_fu_337_p2 = (($signed(sh_amt_reg_1312) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln333_1_fu_949_p2 = (($signed(sh_amt_2_reg_1495) < $signed(12'd54)) ? 1'b1 : 1'b0);

assign icmp_ln333_2_fu_439_p2 = (($signed(sh_amt_4_reg_1350) < $signed(12'd54)) ? 1'b1 : 1'b0);

assign icmp_ln333_fu_342_p2 = (($signed(sh_amt_reg_1312) < $signed(12'd54)) ? 1'b1 : 1'b0);

assign icmp_ln343_1_fu_959_p2 = (($signed(sh_amt_3_fu_954_p2) < $signed(12'd12)) ? 1'b1 : 1'b0);

assign icmp_ln343_2_fu_449_p2 = (($signed(sh_amt_5_fu_444_p2) < $signed(12'd12)) ? 1'b1 : 1'b0);

assign icmp_ln343_fu_352_p2 = (($signed(sh_amt_1_fu_347_p2) < $signed(12'd12)) ? 1'b1 : 1'b0);

assign icmp_ln895_1_fu_1131_p2 = ((tmp_17_fu_1121_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln895_2_fu_757_p2 = ((tmp_19_fu_747_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln895_fu_707_p2 = ((tmp_15_fu_697_p4 == 2'd1) ? 1'b1 : 1'b0);

assign lshr_ln334_1_fu_969_p2 = tmp_6_fu_933_p3 >> zext_ln334_1_fu_965_p1;

assign lshr_ln334_2_fu_459_p2 = tmp_7_fu_423_p3 >> zext_ln334_2_fu_455_p1;

assign lshr_ln334_fu_362_p2 = tmp_2_fu_326_p3 >> zext_ln334_fu_358_p1;

assign o_data_b_V = select_ln1371_2_reg_1461_pp0_iter33_reg;

assign o_data_g_V = ((tmp_21_reg_1540[0:0] === 1'b1) ? sub_ln1371_3_fu_1197_p2 : trunc_ln1371_5_reg_1550);

assign o_data_r_V = select_ln1371_reg_1456_pp0_iter33_reg;

assign or_ln330_1_fu_979_p2 = (icmp_ln330_1_reg_1503 | icmp_ln326_1_reg_1488);

assign or_ln330_2_fu_469_p2 = (icmp_ln330_2_reg_1358 | icmp_ln326_2_reg_1343);

assign or_ln330_fu_372_p2 = (icmp_ln330_reg_1320 | icmp_ln326_reg_1305);

assign or_ln332_1_fu_1009_p2 = (or_ln330_1_fu_979_p2 | icmp_ln332_1_fu_944_p2);

assign or_ln332_2_fu_499_p2 = (or_ln330_2_fu_469_p2 | icmp_ln332_2_fu_434_p2);

assign or_ln332_fu_402_p2 = (or_ln330_fu_372_p2 | icmp_ln332_fu_337_p2);

assign or_ln887_1_fu_1149_p2 = (tmp_16_fu_1113_p3 | icmp_ln895_1_fu_1131_p2);

assign or_ln887_2_fu_775_p2 = (tmp_18_fu_739_p3 | icmp_ln895_2_fu_757_p2);

assign or_ln887_fu_725_p2 = (tmp_14_fu_689_p3 | icmp_ln895_fu_707_p2);

assign p_Result_4_fu_894_p4 = {{reg_V_1_fu_879_p1[62:52]}};

assign p_Result_8_fu_287_p4 = {{reg_V_2_fu_272_p1[62:52]}};

assign p_Result_s_fu_236_p4 = {{reg_V_fu_221_p1[62:52]}};

assign r_V_fu_672_p3 = ((p_Result_5_reg_1294_pp0_iter24_reg[0:0] === 1'b1) ? sub_ln461_fu_667_p2 : select_ln330_reg_1414);

assign reg_V_1_fu_879_p1 = val_assign_1_reg_1466;

assign reg_V_2_fu_272_p1 = val_assign_2_reg_1283;

assign reg_V_fu_221_p1 = val_assign_reg_1268;

assign select_ln1371_2_fu_873_p3 = ((tmp_22_reg_1441[0:0] === 1'b1) ? sub_ln1371_5_fu_868_p2 : trunc_ln1371_8_reg_1451);

assign select_ln1371_fu_862_p3 = ((tmp_20_reg_1426[0:0] === 1'b1) ? sub_ln1371_1_fu_857_p2 : trunc_ln1371_2_reg_1436);

assign select_ln326_1_fu_1060_p3 = ((icmp_ln326_1_reg_1488_pp0_iter31_reg[0:0] === 1'b1) ? 12'd0 : select_ln343_1_fu_1054_p3);

assign select_ln326_2_fu_625_p3 = ((icmp_ln326_2_reg_1343_pp0_iter23_reg[0:0] === 1'b1) ? 12'd0 : select_ln343_2_fu_619_p3);

assign select_ln326_fu_550_p3 = ((icmp_ln326_reg_1305_pp0_iter23_reg[0:0] === 1'b1) ? 12'd0 : select_ln343_fu_544_p3);

assign select_ln330_1_fu_1095_p3 = ((and_ln330_1_fu_1090_p2[0:0] === 1'b1) ? trunc_ln331_1_reg_1482_pp0_iter31_reg : select_ln333_3_fu_1077_p3);

assign select_ln330_2_fu_660_p3 = ((and_ln330_2_fu_655_p2[0:0] === 1'b1) ? trunc_ln331_2_reg_1337_pp0_iter23_reg : select_ln333_5_fu_642_p3);

assign select_ln330_fu_585_p3 = ((and_ln330_fu_580_p2[0:0] === 1'b1) ? trunc_ln331_reg_1299_pp0_iter23_reg : select_ln333_1_fu_567_p3);

assign select_ln333_1_fu_567_p3 = ((and_ln333_1_fu_562_p2[0:0] === 1'b1) ? select_ln336_fu_527_p3 : select_ln326_fu_550_p3);

assign select_ln333_2_fu_1001_p3 = ((and_ln333_2_fu_995_p2[0:0] === 1'b1) ? trunc_ln334_1_fu_975_p1 : 12'd0);

assign select_ln333_3_fu_1077_p3 = ((and_ln333_3_fu_1072_p2[0:0] === 1'b1) ? select_ln336_1_fu_1037_p3 : select_ln326_1_fu_1060_p3);

assign select_ln333_4_fu_491_p3 = ((and_ln333_4_fu_485_p2[0:0] === 1'b1) ? trunc_ln334_2_fu_465_p1 : 12'd0);

assign select_ln333_5_fu_642_p3 = ((and_ln333_5_fu_637_p2[0:0] === 1'b1) ? select_ln336_2_fu_602_p3 : select_ln326_2_fu_625_p3);

assign select_ln333_fu_394_p3 = ((and_ln333_fu_388_p2[0:0] === 1'b1) ? trunc_ln334_fu_368_p1 : 12'd0);

assign select_ln336_1_fu_1037_p3 = ((tmp_11_fu_1030_p3[0:0] === 1'b1) ? 12'd4095 : 12'd0);

assign select_ln336_2_fu_602_p3 = ((tmp_13_fu_595_p3[0:0] === 1'b1) ? 12'd4095 : 12'd0);

assign select_ln336_fu_527_p3 = ((tmp_9_fu_520_p3[0:0] === 1'b1) ? 12'd4095 : 12'd0);

assign select_ln343_1_fu_1054_p3 = ((and_ln343_1_reg_1529[0:0] === 1'b1) ? shl_ln345_1_fu_1049_p2 : select_ln333_2_reg_1524);

assign select_ln343_2_fu_619_p3 = ((and_ln343_2_reg_1409[0:0] === 1'b1) ? shl_ln345_2_fu_614_p2 : select_ln333_4_reg_1404);

assign select_ln343_fu_544_p3 = ((and_ln343_reg_1384[0:0] === 1'b1) ? shl_ln345_fu_539_p2 : select_ln333_reg_1379);

assign select_ln887_1_fu_731_p3 = ((or_ln887_fu_725_p2[0:0] === 1'b1) ? select_ln887_fu_717_p3 : empty_fu_713_p1);

assign select_ln887_2_fu_1141_p3 = ((tmp_16_fu_1113_p3[0:0] === 1'b1) ? 11'd0 : 11'd1023);

assign select_ln887_3_fu_1155_p3 = ((or_ln887_1_fu_1149_p2[0:0] === 1'b1) ? select_ln887_2_fu_1141_p3 : empty_8_fu_1137_p1);

assign select_ln887_4_fu_767_p3 = ((tmp_18_fu_739_p3[0:0] === 1'b1) ? 11'd0 : 11'd1023);

assign select_ln887_5_fu_781_p3 = ((or_ln887_2_fu_775_p2[0:0] === 1'b1) ? select_ln887_4_fu_767_p3 : empty_9_fu_763_p1);

assign select_ln887_fu_717_p3 = ((tmp_14_fu_689_p3[0:0] === 1'b1) ? 11'd0 : 11'd1023);

assign sext_ln329_1_fu_941_p1 = sh_amt_2_reg_1495;

assign sext_ln329_2_fu_431_p1 = sh_amt_4_reg_1350;

assign sext_ln329_fu_334_p1 = sh_amt_reg_1312;

assign sext_ln342_1_fu_1027_p1 = sh_amt_3_reg_1514;

assign sext_ln342_1cast_fu_1045_p1 = sext_ln342_1_fu_1027_p1[11:0];

assign sext_ln342_2_fu_592_p1 = sh_amt_5_reg_1394;

assign sext_ln342_2cast_fu_610_p1 = sext_ln342_2_fu_592_p1[11:0];

assign sext_ln342_fu_517_p1 = sh_amt_1_reg_1369;

assign sext_ln342cast_fu_535_p1 = sext_ln342_fu_517_p1[11:0];

assign sh_amt_1_fu_347_p2 = ($signed(12'd0) - $signed(sh_amt_reg_1312));

assign sh_amt_2_fu_918_p2 = (12'd1075 - exp_V_1_fu_904_p1);

assign sh_amt_3_fu_954_p2 = ($signed(12'd0) - $signed(sh_amt_2_reg_1495));

assign sh_amt_4_fu_311_p2 = (12'd1075 - exp_V_2_fu_297_p1);

assign sh_amt_5_fu_444_p2 = ($signed(12'd0) - $signed(sh_amt_4_reg_1350));

assign sh_amt_fu_260_p2 = (12'd1075 - exp_V_fu_246_p1);

assign shl_ln345_1_fu_1049_p2 = trunc_ln331_1_reg_1482_pp0_iter31_reg << sext_ln342_1cast_fu_1045_p1;

assign shl_ln345_2_fu_614_p2 = trunc_ln331_2_reg_1337_pp0_iter23_reg << sext_ln342_2cast_fu_610_p1;

assign shl_ln345_fu_539_p2 = trunc_ln331_reg_1299_pp0_iter23_reg << sext_ln342cast_fu_535_p1;

assign sub_ln1371_1_fu_857_p2 = (8'd0 - trunc_ln1371_1_reg_1431);

assign sub_ln1371_2_fu_1171_p2 = (11'd0 - select_ln887_3_fu_1155_p3);

assign sub_ln1371_3_fu_1197_p2 = (8'd0 - trunc_ln1371_4_reg_1545);

assign sub_ln1371_4_fu_831_p2 = (11'd0 - select_ln887_5_fu_781_p3);

assign sub_ln1371_5_fu_868_p2 = (8'd0 - trunc_ln1371_7_reg_1446);

assign sub_ln1371_fu_797_p2 = (11'd0 - select_ln887_1_fu_731_p3);

assign sub_ln461_1_fu_1102_p2 = (12'd0 - select_ln330_1_reg_1534);

assign sub_ln461_2_fu_678_p2 = (12'd0 - select_ln330_2_reg_1420);

assign sub_ln461_fu_667_p2 = (12'd0 - select_ln330_reg_1414);

assign tmp_11_fu_1030_p3 = reg_V_1_reg_1471_pp0_iter31_reg[32'd63];

assign tmp_13_fu_595_p3 = reg_V_2_reg_1326_pp0_iter23_reg[32'd63];

assign tmp_14_fu_689_p3 = r_V_fu_672_p3[32'd11];

assign tmp_15_fu_697_p4 = {{r_V_fu_672_p3[11:10]}};

assign tmp_16_fu_1113_p3 = g_V_fu_1107_p3[32'd11];

assign tmp_17_fu_1121_p4 = {{g_V_fu_1107_p3[11:10]}};

assign tmp_18_fu_739_p3 = b_V_fu_683_p3[32'd11];

assign tmp_19_fu_747_p4 = {{b_V_fu_683_p3[11:10]}};

assign tmp_2_fu_326_p3 = {{1'd1}, {trunc_ln318_fu_323_p1}};

assign tmp_6_fu_933_p3 = {{1'd1}, {trunc_ln318_1_fu_930_p1}};

assign tmp_7_fu_423_p3 = {{1'd1}, {trunc_ln318_2_fu_420_p1}};

assign tmp_9_fu_520_p3 = reg_V_reg_1288_pp0_iter23_reg[32'd63];

assign trunc_ln310_1_fu_882_p1 = reg_V_1_fu_879_p1[62:0];

assign trunc_ln310_2_fu_275_p1 = reg_V_2_fu_272_p1[62:0];

assign trunc_ln310_fu_224_p1 = reg_V_fu_221_p1[62:0];

assign trunc_ln318_1_fu_930_p1 = reg_V_1_reg_1471[51:0];

assign trunc_ln318_2_fu_420_p1 = reg_V_2_reg_1326[51:0];

assign trunc_ln318_fu_323_p1 = reg_V_reg_1288[51:0];

assign trunc_ln331_1_fu_908_p1 = reg_V_1_fu_879_p1[11:0];

assign trunc_ln331_2_fu_301_p1 = reg_V_2_fu_272_p1[11:0];

assign trunc_ln331_fu_250_p1 = reg_V_fu_221_p1[11:0];

assign trunc_ln334_1_fu_975_p1 = lshr_ln334_1_fu_969_p2[11:0];

assign trunc_ln334_2_fu_465_p1 = lshr_ln334_2_fu_459_p2[11:0];

assign trunc_ln334_fu_368_p1 = lshr_ln334_fu_362_p2[11:0];

assign xor_ln326_1_fu_1085_p2 = (icmp_ln326_1_reg_1488_pp0_iter31_reg ^ 1'd1);

assign xor_ln326_2_fu_650_p2 = (icmp_ln326_2_reg_1343_pp0_iter23_reg ^ 1'd1);

assign xor_ln326_fu_575_p2 = (icmp_ln326_reg_1305_pp0_iter23_reg ^ 1'd1);

assign xor_ln330_1_fu_983_p2 = (or_ln330_1_fu_979_p2 ^ 1'd1);

assign xor_ln330_2_fu_473_p2 = (or_ln330_2_fu_469_p2 ^ 1'd1);

assign xor_ln330_fu_376_p2 = (or_ln330_fu_372_p2 ^ 1'd1);

assign xor_ln332_1_fu_1015_p2 = (or_ln332_1_fu_1009_p2 ^ 1'd1);

assign xor_ln332_2_fu_505_p2 = (or_ln332_2_fu_499_p2 ^ 1'd1);

assign xor_ln332_fu_408_p2 = (or_ln332_fu_402_p2 ^ 1'd1);

assign xor_ln333_1_fu_1067_p2 = (icmp_ln333_1_reg_1509 ^ 1'd1);

assign xor_ln333_2_fu_632_p2 = (icmp_ln333_2_reg_1389 ^ 1'd1);

assign xor_ln333_fu_557_p2 = (icmp_ln333_reg_1364 ^ 1'd1);

assign y_V_fu_211_p2 = ($signed(11'd2032) + $signed(zext_ln68_fu_208_p1));

assign zext_ln334_1_fu_965_p1 = $unsigned(sext_ln329_1_fu_941_p1);

assign zext_ln334_2_fu_455_p1 = $unsigned(sext_ln329_2_fu_431_p1);

assign zext_ln334_fu_358_p1 = $unsigned(sext_ln329_fu_334_p1);

assign zext_ln68_fu_208_p1 = i_data_y_V_read_reg_1209_pp0_iter6_reg;

endmodule //convert_10to8
